# Generated by Django 4.2.1 on 2023-05-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('TCA', 'Termo de Compromisso Ambiental'), ('AA', 'Autorização Ambiental')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data_geracao', models.DateField(null=True)),
                ('protocolo', models.CharField(blank=True, max_length=32, null=True)),
                ('categoria_relatorio', models.ManyToManyField(to='relatorios.categoriarelatorio')),
            ],
        ),
    ]
