# Generated by Django 4.2.1 on 2023-05-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_alter_relatorio_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
