# Generated by Django 4.2.1 on 2023-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='restricao',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
