# Generated by Django 4.2.1 on 2023-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0003_alter_autorizacao_area_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='restricao',
            field=models.CharField(choices=[('Preservação no interior do lote/Outros', 'Preservação no interior do lote/Outros'), ('Preservação no interior do lote/Motivo 1', 'Preservação no interior do lote/Motivo 1'), ('Preservação no interior do lote/Motivo 2', 'Preservação no interior do lote/Motivo 2'), ('Preservação no interior do lote/Motivo 3', 'Preservação no interior do lote/Motivo 3')], max_length=50),
        ),
    ]
