# Generated by Django 4.2.1 on 2023-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacao', '0004_alter_autorizacao_restricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='restricao',
            field=models.CharField(max_length=100),
        ),
    ]
